version: '3'

networks:
  app-tier:
    driver: bridge

services:
  nuxt:
    build:
      context: .
    restart: unless-stopped
    networks:
      - app-tier

  caddy:
    image: caddy:latest
    restart: unless-stopped
    environment:
      - SERVER_NAME=${SERVER_NAME:-localhost}
    cap_add:
      - NET_ADMIN
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-tier

volumes:
  caddy_data:
  caddy_config:
